config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "taxes#index"

  resources :taxes, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/taxes_controller.rb
class TaxesController < ApplicationController
  def index
    monthly_income = params[:monthly_income] ? params[:monthly_income].gsub(',', '').to_i : 0
    salary_paid_for_insurance = params[:salary_paid_for_insurance] ? params[:salary_paid_for_insurance].gsub(',', '').to_i : 0
    number_dependents = params[:number_dependents] ? params[:number_dependents].gsub(',', '').to_i : 0
    @income_tax = TaxService::CalcPersonalIncomeTax.new.call(
      monthly_income: monthly_income,
      salary_paid_for_insurance: salary_paid_for_insurance,
      number_dependents: number_dependents
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CalculatePersonalIncomeTax</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/taxes/_income_tax.html.erb
$('.income-tax').html('abc');

app/views/taxes/index.html.erb
<div class="container">
  <%= form_tag taxes_path, method: :get, remote: true do %>
    <h3>Enter the monthly income data for the monthly provisional tax amount.</h3>
    <div class="form-group">
      <label>Monthly income</label>
      <%= text_field_tag :monthly_income, 0, class: 'form-control number', required: true %>
    </div>
    <div class="form-group">
      <label>Salary paid for insurance</label>
      <%= text_field_tag :salary_paid_for_insurance, 0, class: 'form-control number', required: true %>
    </div>
    <div class="form-group">
      <label>Number of dependents</label>
      <%= text_field_tag :number_dependents, 0, class: 'form-control number', required: true %>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  <% end %>
  <br />
  <div class="income-tax">Personal income tax is: <%= number_with_delimiter(@income_tax) %> VND</div>
</div>

<script>
  $('.number').keyup(function(event) {

    // skip for arrow keys
    if(event.which >= 37 && event.which <= 40) return;

    // format number
    $(this).val(function(index, value) {
      return value
      .replace(/\D/g, "")
      .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
      ;
    });
  });
</script>

app/views/taxes/index.js.erb
$('.income-tax').html('Personal income tax is: <%= number_with_delimiter(@income_tax) %> VND');